repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest stable version or a specific version known to be compatible
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0  # Example version
    hooks:
      - id: eslint
  # Add more repositories and hooks as needed
